### PR TITLE
✨ QRCode API

### PR DESCRIPTION
**Pull request by rezk2ll**
## feature
- requests a new access_token using SSO and matrix
- generates an SVG image containing the access_token and a magic link to the mobile application.

### Prerequisites
**the user must be connected**
**the web auth cookie must be included in the request: ie `lemonldap`**

example:
```
twake.chat://login?access_token=123456
```
closes https://github.com/linagora/twake-on-matrix/issues/1764

# demo
## API using Postman
qrcode

## qrcode decode using mobile ( without mobile magic link )

https://github.com/user-attachments/assets/1d2fa357-f1e9-43b1-9b31-f8ef1faa33b8

### CODE REVIEW

**Comment by guimard** [comment]
Hi @rezk2ll : which access_token do you display here ? Remember that an access token owns to only one device

**Comment by hoangdat** [comment]
hi @rezk2ll , what kind of token in QR code?

**Comment by hoangdat** [comment]
hi @rezk2ll , we want to generate QR code ourselves. Which endpoint we need to use?

**Comment by rezk2ll** [comment]
> hi @rezk2ll , we want to generate QR code ourselves. Which endpoint we need to use?
> 

Hello @hoangdat ,

the endpoint is /_twake/v1/qrcode

More details on the swagger docs here
https://linagora.github.io/ToM-server/#/QR%20Code/get__twake_v1_qrcode

It requires the lemonldap cookie to be present in the request.

**Comment by rezk2ll** [comment]
> hi @rezk2ll , what kind of token in QR code?

it is an access_token obtained from matrix using the /_matrix/client/v3/login endpoint

**Comment by hoangdat** [comment]
> the endpoint is /_twake/v1/qrcode

But we only need the token, we want to generate our QR code from our self, to put it to our component view

**Comment by rezk2ll** [comment]
> > the endpoint is /_twake/v1/qrcode
> 
> But we only need the token, we want to generate our QR code from our self, to put it to our component view

The endpoint returns a ready SVG image that can be rendered freely on the front end.

**Comment by hoangdat** [comment]
hi @guimard , what do you think it is security issue if access_token stay in QR code. 
From my point of view, any scanner can scan it and extract it, it is a huge risk.

**Comment by guimard** [comment]
Hi, there is a risk when QR code is displayed.
The best would be to follow Whatsapp way : the QR code has to be scanned from a valid device to validate new device but it's harder to build

**Pull request merged**
